export default {
	routes:[
		{
			name:'show',
			path:'/show/:user_id',
			component:require('./views/main.vue'),
		},
		{
			name:'home',
			path:'/home',
			component:require("./views/home.vue")
		},
		{
			name:'login',
			path:'/loginPage',
			component:require("./views/login.vue")
		},
		{
			name:'signIn',
			path:'/signInPage',
			component: require("./views/signIn.vue")
		},
		{
			name:'create',
			path:'/create/:user_id',
			component:require("./views/create.vue")
		},
		{
			name:'mysurvey',
			path:'/mysurvey/:user_id',
			component:require("./views/mySurvey.vue")
		},
		{
			name:'template',
			path:'/template',
			component:require("./views/template.vue")
		},
		{
			name:'edit',
			path:'/editpage/:user_id/:survey_id',
			component:require('./views/edit_page.vue')
		},
		{
			name:'fill',
			path:'/fill/:survey_id',
			component:require('./views/fill.vue')
		},
		{
			name:'analyze',
			path:'/analyze/:survey_id',
			component:require('./views/analyze.vue')
		},
		{ path: "/", redirect: '/home' }
	]
}